### PR TITLE
Fix `escapeTag` for non-string replacement values.

### LINKED ISSUE #538: allowCreate attribute not set correctly
```
samlify.ServiceProvider({
	metadata: metadata,
	allowCreate: 'true',
})
```

If I don't set the `allowCreate` property the SAML request XML will have an empty attribute, which causes it to be invalid:
`<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" AllowCreate=""/>`

If I set it to `true` (as a boolean) as specified in `ServiceProviderSettings` it crashes due to `string.replace is not a function`.
Only if I set it to the string `"true"` does it work. So this is my workaround, but it's of course not ideal.

Thanks for all your work on this library @tngan 🙏

### PR DESCRIPTION
**Pull request by mastermatt**
Fixes #538 for bug introduced in #523 (v2.8.11).

The values passed to `replaceTagsByValue` are not always strings, notably `allowCreate` is a boolean. These values need to be cast to their string equivalents before being passed into `xmlEscape`.

It's worth calling out the test suite has not been passing since the bug was introduced, it caused four tests to start failing. I did not add any new tests, however, the test suite passes again with these changes. 

Other changes, return type of `getDigestMethod`  and test updates, were related to the recent update of `xml-crypto`.

cc @tngan  @Munawwar @D-32

### CODE REVIEW

**Comment by dotanalter** [comment]
This is a critical fix.
Please review this PR @tngan

**Comment by tngan** [comment]
@mastermatt thanks for the PR, bump v2.9.1 to npm

**Comment by Munawwar** [comment]
I am seeing this after a year. Oops. I couldn't run the test suite properly without it hanging for some reason iirc. Glad this was fixed.
